apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: wanderlust
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: huzaifafev/wanderlust-frontend-beta:v2.21.1
          ports:
            - containerPort: 5173
          command: ["npm", "run", "dev", "--", "--host"]

#Since you didn’t define an imagePullSecrets, Kubernetes assumes the image is public (on Docker Hub).
#If your image is public → no problem, it will pull fine.
#If your image is private (Docker Hub private repo, ECR, GCR, etc.) → you must create a secret and reference it using
#imagPullSecret

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: wanderlust
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP
      nodePort: 31000
